[tool.poetry]
name = "camera-to-vectordb"
version = "0.1.0"
description = ""
authors = ["David Aronchick <aronchick@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ruff = "^0.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
